In [7]:
#classification problem
#reading the historical data

import pandas as pd
df_loan=pd.read_csv('i:\\train_loan.csv')
df_loan.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [8]:
#to view summary of numerical data 

df_loan.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       614.000000         614.000000  592.000000         600.00000   
mean       5403.459283        1621.245798  146.412162         342.00000   
std        6109.041673        2926.248369   85.587325          65.12041   
min         150.000000           0.000000    9.000000          12.00000   
25%        2877.500000           0.000000  100.000000         360.00000   
50%        3812.500000        1188.500000  128.000000         360.00000   
75%        5795.000000        2297.250000  168.000000         360.00000   
max       81000.000000       41667.000000  700.000000         480.00000   

       Credit_History  
count      564.000000  
mean         0.842199  
std          0.364878  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

In [9]:
#to view summary of categorical data only

df_loan.describe(include='object')

Loan_ID Gender Married Dependents Education Self_Employed  \
count        614    601     611        599       614           582   
unique       614      2       2          4         2             2   
top     LP002115   Male     Yes          0  Graduate            No   
freq           1    489     398        345       480           500   

       Property_Area Loan_Status  
count            614         614  
unique             3           2  
top        Semiurban           Y  
freq             233         422

In [10]:
#to view summary of both numerical and categorical data

#df_loan.describe(include='all')

In [11]:
#Prepare X
X=df_loan.drop(['Loan_ID', 'Loan_Status'], axis=1)
X.head()

Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
0   Male      No          0      Graduate            No             5849   
1   Male     Yes          1      Graduate            No             4583   
2   Male     Yes          0      Graduate           Yes             3000   
3   Male     Yes          0  Not Graduate            No             2583   
4   Male      No          0      Graduate            No             6000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0         NaN             360.0             1.0   
1             1508.0       128.0             360.0             1.0   
2                0.0        66.0             360.0             1.0   
3             2358.0       120.0             360.0             1.0   
4                0.0       141.0             360.0             1.0   

  Property_Area  
0         Urban  
1         Rural  
2         Urban  
3         Urban  
4         Urban

In [12]:
#Preapare y

y=df_loan['Loan_Status']
y.head()

0    Y
1    N
2    Y
3    Y
4    Y
Name: Loan_Status, dtype: object

In [13]:
#binarize the values of Loan_Status or 'y' between 0 & 1
#N=0 and Y=1
from sklearn.preprocessing import LabelBinarizer
lb=LabelBinarizer()
y=lb.fit_transform(y)
y[0:5]

array([[1],
       [0],
       [1],
       [1],
       [1]], dtype=int32)

In [14]:
#Checking missing values in X

X.isnull().sum()

Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
dtype: int64

In [15]:
#Filling missing values in categorical column
#counting frequency of each category in 'Gender' column

#X['Gender'].value_counts() can be written as

X.Gender.value_counts()

Male      489
Female    112
Name: Gender, dtype: int64

In [16]:
#fill missing values in 'Gender' column with highest frequency value i.e. 'Male'
X.Gender.fillna('Male', inplace=True)

#checking missing values
X.isnull().sum()

Gender                0
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
dtype: int64

In [17]:
#filling missing data in 'Married'

X.Married.value_counts()

Yes    398
No     213
Name: Married, dtype: int64

In [18]:
#replace missing values in 'Married' with 'Yes'

#df_loan.Married=df_loan.Married.fillna('Yes')

X.Married.fillna('Yes', inplace=True)

X.isnull().sum()

Gender                0
Married               0
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
dtype: int64

In [19]:
#filling missing values in 'Dependents'

X.Dependents.value_counts()

0     345
1     102
2     101
3+     51
Name: Dependents, dtype: int64

In [20]:
#Now fill the missing values in 'Dependents' with 0
X.Dependents.fillna(0, inplace=True)

X.isnull().sum()

Gender                0
Married               0
Dependents            0
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
dtype: int64

In [21]:
#filling missing values in 'Self_Employed'

X.Self_Employed.value_counts()

No     500
Yes     82
Name: Self_Employed, dtype: int64

In [22]:
#fill missing values in 'Self_Employed' with No

X.Self_Employed.fillna('No', inplace=True)
X.isnull().sum()

Gender                0
Married               0
Dependents            0
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
dtype: int64

In [23]:
#filling missing data in 'LoanAmount' with their mean

import numpy as np
m=np.mean(X.LoanAmount)
X.LoanAmount.fillna(m, inplace=True)

X.isnull().sum()

Gender                0
Married               0
Dependents            0
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
dtype: int64

In [24]:
#Filling missing values in 'Loan_Amount_Term'

X.Loan_Amount_Term.fillna(np.mean(X.Loan_Amount_Term), inplace=True)

X.isnull().sum()

Gender                0
Married               0
Dependents            0
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term      0
Credit_History       50
Property_Area         0
dtype: int64

In [25]:
#filling missing in 'Credit_History'

X.Credit_History.value_counts()

1.0    475
0.0     89
Name: Credit_History, dtype: int64

In [26]:
#filling missing data in 'Credit_History' with 1

X.Credit_History.fillna(1, inplace=True)

X.isnull().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
dtype: int64

In [27]:
X.LoanAmount.head()

0    146.412162
1    128.000000
2     66.000000
3    120.000000
4    141.000000
Name: LoanAmount, dtype: float64

In [28]:
#transforming categorical data into numerical one

X=pd.get_dummies(X)
X.head()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0  146.412162             360.0   
1             4583             1508.0  128.000000             360.0   
2             3000                0.0   66.000000             360.0   
3             2583             2358.0  120.000000             360.0   
4             6000                0.0  141.000000             360.0   

   Credit_History  Gender_Female  Gender_Male  Married_No  Married_Yes  \
0             1.0              0            1           1            0   
1             1.0              0            1           0            1   
2             1.0              0            1           0            1   
3             1.0              0            1           0            1   
4             1.0              0            1           1            0   

   Dependents_0  ...  Dependents_1  Dependents_2  Dependents_3+  \
0             0  ...             0             0              0   
1             0  ...             1             0              0   
2             0  ...             0             0              0   
3             0  ...             0             0              0   
4             0  ...             0             0              0   

   Education_Graduate  Education_Not Graduate  Self_Employed_No  \
0                   1                       0                 1   
1                   1                       0                 1   
2                   1                       0                 0   
3                   0                       1                 1   
4                   1                       0                 1   

   Self_Employed_Yes  Property_Area_Rural  Property_Area_Semiurban  \
0                  0                    0                        0   
1                  0                    1                        0   
2                  1                    0                        0   
3                  0                    0                        0   
4                  0                    0                        0   

   Property_Area_Urban  
0                    1  
1                    0  
2                    1  
3                    1  
4                    1  

[5 rows x 21 columns]

In [29]:
#splitting the data into: training set and testing set

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test=train_test_split(X,y, test_size=0.25)

In [30]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(460, 21)
(154, 21)
(460, 1)
(154, 1)


In [31]:
#Implementing classification algorithm 
#Implementing LogisticRegression

from sklearn.linear_model import LogisticRegression

LR=LogisticRegression()
LR.fit(X_train, y_train)

C:\Users\Sonu\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Sonu\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [32]:
#Applying Support Vector Classifier (SVC)

from sklearn.svm import SVC
svc=SVC()
svc.fit(X_train, y_train)

C:\Users\Sonu\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Sonu\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [33]:
#Applying Decision Tree Classifier

from sklearn.tree import DecisionTreeClassifier

dtc=DecisionTreeClassifier()
dtc.fit(X_train, y_train)


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [34]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(X_train, y_train)

C:\Users\Sonu\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None, var_smoothing=1e-09)

In [35]:
print('Score of LogisticRegression:', LR.score(X_test, y_test))
print('Score of SVC:', svc.score(X_test, y_test))
print('Score of Decision Tree Classifier:', dtc.score(X_test, y_test))
print('Score of GaussianNB:', nb.score(X_test, y_test))

Score of LogisticRegression: 0.7792207792207793
Score of SVC: 0.6688311688311688
Score of Decision Tree Classifier: 0.6818181818181818
Score of GaussianNB: 0.7532467532467533


In [ ]:
#since score of LogisticRegression is highest
#We can say that LogicticRegression algorithm is best for this problem

LR_predict=LR.predict(X_test)

df_LR=pd.DataFrame({'Actual Data': y_test, 'Predicted Data': LR_predict} )
df_LR.to_csv('i:\\Loan_prediction_LR.csv')

In [36]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix

LR_pred=LR.predict(X_test)
print("Score of LinearRegression Model:", LR.score(X_test, y_test))

#preparing confusion matrix on LinearRegression algorithm

conf_LR=confusion_matrix(y_test, LR_pred)
print("Confusion Matrix of LinearRegression")

df_lr=pd.DataFrame(conf_LR, columns=['No', 'Yes'],  index=['No', 'Yes'])
print(df_lr)

Score of LinearRegression Model: 0.7792207792207793
Confusion Matrix of LinearRegression
     No  Yes
No   23   28
Yes   6   97


In [ ]:
#in X_test
#Total No=47
# Total Yes=107


In [37]:
dtc_pred=dtc.predict(X_test)
print("Score of Decision Tree Classifier Model:", dtc.score(X_test, y_test))

#preparing confusion matrix on LinearRegression algorithm

conf_dtc=confusion_matrix(y_test, dtc_pred)
print("Confusion Matrix of Decision Tree Classifier")

df_dtc=pd.DataFrame(conf_dtc, columns=['No', 'Yes'],  index=['No', 'Yes'])
print(df_dtc)

Score of Decision Tree Classifier Model: 0.6818181818181818
Confusion Matrix of Decision Tree Classifier
     No  Yes
No   29   22
Yes  27   76


In [38]:
nb_pred=nb.predict(X_test)
print("Score of GaussianNB:", nb.score(X_test, y_test))

#preparing confusion matrix on GaussianNB algorithm

conf_nb=confusion_matrix(y_test, nb_pred)
print("Confusion Matrix of GaussianNB")

df_nb=pd.DataFrame(conf_nb, columns=['No', 'Yes'],  index=['No', 'Yes'])
print(df_nb)

Score of GaussianNB: 0.7532467532467533
Confusion Matrix of GaussianNB
     No  Yes
No   26   25
Yes  13   90


In [39]:
from sklearn.neighbors import KNeighborsClassifier
knc=KNeighborsClassifier()
knc.fit(X_train, y_train)

print("Score of KNeighborsClassifier:", knc.score(X_test, y_test))
knc_pred=knc.predict(X_test)

#preparing confusion matrix on KNeighborsClassifier algorithm

conf_knc=confusion_matrix(y_test, knc_pred)
print("Confusion Matrix of KNeighborsClassifier")

df_knc=pd.DataFrame(conf_knc, columns=['No', 'Yes'],  index=['No', 'Yes'])
print(df_knc)

Score of KNeighborsClassifier: 0.5454545454545454
Confusion Matrix of KNeighborsClassifier
     No  Yes
No    9   42
Yes  28   75


C:\Users\Sonu\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


In [43]:
#Now we can say that LogicticRegression model/algorithm has the highest score and No. of incorrect
#prediction in 'Yes' is also very low i.e. only 1. 

#Now imporoving the LogisticRegression Model

#Printing probability of each class on LogisticRegression Model

LR_prob=LR.predict_proba(X_test)
df45=pd.DataFrame(LR_prob, columns=['0', '1'])
df45[0:5]

0         1
0  0.078904  0.921096
1  0.258166  0.741834
2  0.925903  0.074097
3  0.297876  0.702124
4  0.189725  0.810275

In [44]:
print('Predicted by LogicticRegression')
LR_pred[0:5]

Predicted by LogicticRegression


array([1, 1, 0, 1, 1], dtype=int32)

In [45]:
conf_LR

array([[23, 28],
       [ 6, 97]], dtype=int64)

In [58]:
#printing first 5 probabilities of LogisticRegression model
LR_prob[0:5]

array([[0.07890391, 0.92109609],
       [0.25816588, 0.74183412],
       [0.92590286, 0.07409714],
       [0.29787613, 0.70212387],
       [0.18972526, 0.81027474]])

In [57]:
LR_class=binarize(LR_prob, 0.60)
LR_class[0:5]

array([[0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.]])

In [59]:
LR_class1=binarize(LR_prob, 0.80)
LR_class1[0:5]

array([[0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.]])

In [61]:
#confusion matrix of LogisticRegression Model on threshold=0.5
conf_LR

#For '0' class, wrong prediction=28
#For '1' class, wrong prediction=6

array([[23, 28],
       [ 6, 97]], dtype=int64)

In [60]:
#Improving classification model

#The threshold value of probability is 0.5

#class imbalancing of a classification model can be improved by increasing or decreasing the threshold
#value of probability
#Here we are increasing the threshold value of probability to 0.6
from sklearn.preprocessing import binarize

LR_class=binarize(LR_prob, 0.60)
LR_class1=LR_class[:,1]
LR_class_int=LR_class1.astype(int)
modified_conf_LR=confusion_matrix(y_test, LR_class_int)
modified_conf_LR

array([[27, 24],
       [11, 92]], dtype=int64)

In [62]:
LR_class=binarize(LR_prob, 0.65)
LR_class11=LR_class[:,1]
LR_class_int1=LR_class11.astype(int)
modified_conf_LR1=confusion_matrix(y_test, LR_class_int1)
modified_conf_LR1

array([[30, 21],
       [16, 87]], dtype=int64)

In [63]:
LR_class=binarize(LR_prob, 0.70)
LR_class111=LR_class[:,1]
LR_class_int11=LR_class111.astype(int)
modified_conf_LR11=confusion_matrix(y_test, LR_class_int11)
modified_conf_LR11

array([[32, 19],
       [28, 75]], dtype=int64)